### PR TITLE
Add a Banglore based popular vendor

### PR DESCRIPTION
**Pull request by chrishna1**

### CODE REVIEW

**Comment by chrishna1** [comment]
Thanks @anujdeshpande for building a wonderful community and quickly merging the pr:)

Just a thought. This list is getting bigger and won't help a newcomer in deciding which one to go with. We can assign some label like "recommended" to a few of them and show them on top.

**Comment by anujdeshpande** [comment]
@chrishna1 good idea. might need some work though - will have to figure how to do this in the table library we are using for react/docusaurus.

**Comment by anujdeshpande** [comment]
On second thoughts ... it would be nice to have a form which creates a PR. Having to edit a json file is not the best UI for this list. There we could do a drop down of the categories.

(We earlier had a plain markdown file, but that was no good for making the table sortable per column)

**Comment by chrishna1** [comment]
Can you check Airtable? I think that's well suited for such use cases. It allows you to create a table and embed it on your site. e.g look at https://layoffs.fyi/ it also provides you an easy form for end user to submit data(https://layoffs.fyi/share-intel/).

It has a generous free tier as well.

**Comment by anujdeshpande** [comment]
@chrishna1 we used a couple of closed source platforms before settling on docusaurus - every time we changed tools, we lost contributors. It's better now because some folks posted about us on Twitter etc - so we got more eyeballs - but I'd rather not use tools that are based on closed standards.

**Pull request merged**
